HC-51: job-spec and hysds-io JSON validation
hysds/hysds_commons pull request #3
Opened 2019-07-11 18:28 UTC by mcayanan

- Added schemas for the job-spec and hysds-io
- Added unit tests to test the schemas
- Updated setup.py in HySDS Commons to install the jsonschema module
- Added a validate.py, which is based off of the one in the
container-builder repo.

2019-07-11 19:03 UTC, pymonger requested changes
@mcayanan looks good. But the circleci check didn't run any tests (https://circleci.com/gh/hysds/hysds_commons/19?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). Could you update the circleci config so that it runs pytest so that your tests are found?

2019-07-11 22:32 UTC, mcayanan commented
@pymonger Check out circleci now. I think I got the pytest stuff added in there now:

https://circleci.com/gh/hysds/hysds_commons/32

2019-07-12 14:49 UTC, pymonger commented
Closing to redo PR with 2 Jira issues.

2019-07-12 15:00 UTC, pymonger approved these changes

2019-07-12 15:06 UTC, merged