Passthru publish_override_ok in resolve_hysds_job
hysds/hysds_commons pull request #55
Opened 2023-05-22 22:42 UTC by joshgarde

Part of HC-473 work

2024-03-14 21:56 UTC, pymonger submitted a review, later dismissed
LGTM. @mcayanan ?

2024-03-14 21:58 UTC, DustinKLo submitted a review, later dismissed

2024-03-14 22:06 UTC, mcayanan requested changes
Do we need a version bump to 1.1.2?

https://github.com/hysds/hysds_commons/blob/8f7b72d49ae77e46b2787572017d668a87a3d360/hysds_commons/__init__.py#L6

Also, appears that the branch needs to get sync'd with develop first before merging?

2024-03-14 23:07 UTC, DustinKLo requested changes, later dismissed

2024-03-14 23:07 UTC, DustinKLo commented on hysds_commons/__init__.py
> +__version__ = "1.0.16"
should be `1.1.2`

2024-03-15 00:10 UTC, pymonger approved these changes

2024-03-15 00:11 UTC, mcayanan approved these changes

2024-03-15 00:15 UTC, DustinKLo approved these changes

2024-03-15 00:59 UTC, pymonger approved these changes

2024-03-15 01:00 UTC, merged